language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry phpenv rehash

script:
  - composer run check
  - composer run test

after_script:
  - |
    if [ -f "build/logs/clover.xml" ]; then
      composer run upload-coveralls
      composer run upload-scrutinizer
    fi
