language: php

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: nightly

install:
  - if [[ $TRAVIS_PHP_VERSION == hhvm ]]; then composer require --dev "phpunit/phpunit:^5"; fi
  - if [[ $TRAVIS_PHP_VERSION == 7.0 ]]; then composer require --dev "phpunit/phpunit:^6"; fi
  - if [[ $TRAVIS_PHP_VERSION == 5.6 ]]; then composer require --dev "phpunit/phpunit:^5"; fi
  - composer install

script:
  - composer run check
  - composer run test

after_script:
  - |
    if [ -f "build/logs/clover.xml" ]; then
      composer run upload-coveralls
      composer run upload-scrutinizer
    fi

notifications:
  email: false
