language: php

sudo: false
dist: trusty

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: nightly

install:
  - composer install
  - |
     if [[ $TRAVIS_PHP_VERSION == hhvm ]]; then
      curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
     fi

script:
  - ./vendor/bin/phpcs --standard=psr2 -sp src/
  - |
    if [[ $TRAVIS_PHP_VERSION == hhvm ]]; then
      ~/.phpenv/versions/hhvm/bin/phpunit
    else
      ./vendor/bin/phpunit
    fi

after_script:
  - |
    if [ -f "build/logs/clover.xml" ]; then
      if [ -f "vendor/bin/coveralls" ]; then
        ./vendor/bin/coveralls -v
      else
        ./vendor/bin/php-coveralls -v
      fi
      ./vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
    fi
