os: linux
dist: bionic
language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  # https://github.com/php-coveralls/php-coveralls
  - wget https://github.com/php-coveralls/php-coveralls/releases/latest/download/php-coveralls.phar
  # https://scrutinizer-ci.com/docs/tools/external-code-coverage/
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install

script:
  - ./vendor/bin/phpunit
  # this checks that the source code follows the syntax rules
  - ./vendor/bin/phpcs
  # this checks that the source code follows the Symfony Code Syntax rules
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v
  # this checks that the composer.json and composer.lock files are valid
  - composer validate --strict

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "7.4" && -f "build/logs/clover.xml" ]]; then
      php php-coveralls.phar -v
      php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    fi
