language: php

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer validate

install:
  - composer install --no-interaction --no-progress

before_script:
  - phpenv rehash

script:
  - composer run check
  - composer run test

after_script:
  - |
    if [ -f "build/logs/clover.xml" ]; then
      composer run upload-coveralls
      composer run upload-scrutinizer
    fi

notifications:
  email: false
